/**
 * 单词库 - 每个级别的单词和对应的中文含义
 * 每个后续级别的单词数量是前一级的2倍
 */
const VOCABULARY = {
    // 第1关：5个单词
    1: [
        { english: "apple", chinese: "苹果" },
        { english: "book", chinese: "书" },
        { english: "cat", chinese: "猫" },
        { english: "dog", chinese: "狗" },
        { english: "elephant", chinese: "大象" }
    ],
    
    // 第2关：10个单词
    2: [
        { english: "water", chinese: "水" },
        { english: "fire", chinese: "火" },
        { english: "earth", chinese: "地球" },
        { english: "wind", chinese: "风" },
        { english: "sun", chinese: "太阳" },
        { english: "moon", chinese: "月亮" },
        { english: "star", chinese: "星星" },
        { english: "sky", chinese: "天空" },
        { english: "ocean", chinese: "海洋" },
        { english: "mountain", chinese: "山" }
    ],
    
    // 第3关：20个单词
    3: [
        { english: "happy", chinese: "快乐的" },
        { english: "sad", chinese: "悲伤的" },
        { english: "fast", chinese: "快速的" },
        { english: "slow", chinese: "缓慢的" },
        { english: "big", chinese: "大的" },
        { english: "small", chinese: "小的" },
        { english: "hot", chinese: "热的" },
        { english: "cold", chinese: "冷的" },
        { english: "new", chinese: "新的" },
        { english: "old", chinese: "旧的" },
        { english: "good", chinese: "好的" },
        { english: "bad", chinese: "坏的" },
        { english: "high", chinese: "高的" },
        { english: "low", chinese: "低的" },
        { english: "long", chinese: "长的" },
        { english: "short", chinese: "短的" },
        { english: "young", chinese: "年轻的" },
        { english: "old", chinese: "年老的" },
        { english: "beautiful", chinese: "美丽的" },
        { english: "ugly", chinese: "丑陋的" }
    ],
    
    // 第4关：40个单词
    4: [
        { english: "run", chinese: "跑步" },
        { english: "walk", chinese: "走路" },
        { english: "jump", chinese: "跳跃" },
        { english: "swim", chinese: "游泳" },
        { english: "fly", chinese: "飞行" },
        { english: "eat", chinese: "吃" },
        { english: "drink", chinese: "喝" },
        { english: "sleep", chinese: "睡觉" },
        { english: "read", chinese: "阅读" },
        { english: "write", chinese: "写作" },
        { english: "listen", chinese: "听" },
        { english: "speak", chinese: "说" },
        { english: "watch", chinese: "观看" },
        { english: "see", chinese: "看见" },
        { english: "touch", chinese: "触摸" },
        { english: "smell", chinese: "闻" },
        { english: "taste", chinese: "品尝" },
        { english: "think", chinese: "思考" },
        { english: "feel", chinese: "感觉" },
        { english: "know", chinese: "知道" },
        { english: "understand", chinese: "理解" },
        { english: "remember", chinese: "记忆" },
        { english: "forget", chinese: "忘记" },
        { english: "learn", chinese: "学习" },
        { english: "teach", chinese: "教导" },
        { english: "help", chinese: "帮助" },
        { english: "work", chinese: "工作" },
        { english: "play", chinese: "玩耍" },
        { english: "start", chinese: "开始" },
        { english: "stop", chinese: "停止" },
        { english: "open", chinese: "打开" },
        { english: "close", chinese: "关闭" },
        { english: "come", chinese: "来" },
        { english: "go", chinese: "去" },
        { english: "buy", chinese: "购买" },
        { english: "sell", chinese: "销售" },
        { english: "find", chinese: "寻找" },
        { english: "lose", chinese: "丢失" },
        { english: "give", chinese: "给予" },
        { english: "take", chinese: "拿取" }
    ],
    
    // 第5关：80个单词
    5: [
        { english: "Monday", chinese: "星期一" },
        { english: "Tuesday", chinese: "星期二" },
        { english: "Wednesday", chinese: "星期三" },
        { english: "Thursday", chinese: "星期四" },
        { english: "Friday", chinese: "星期五" },
        { english: "Saturday", chinese: "星期六" },
        { english: "Sunday", chinese: "星期日" },
        { english: "January", chinese: "一月" },
        { english: "February", chinese: "二月" },
        { english: "March", chinese: "三月" },
        { english: "April", chinese: "四月" },
        { english: "May", chinese: "五月" },
        { english: "June", chinese: "六月" },
        { english: "July", chinese: "七月" },
        { english: "August", chinese: "八月" },
        { english: "September", chinese: "九月" },
        { english: "October", chinese: "十月" },
        { english: "November", chinese: "十一月" },
        { english: "December", chinese: "十二月" },
        { english: "spring", chinese: "春天" },
        { english: "summer", chinese: "夏天" },
        { english: "autumn", chinese: "秋天" },
        { english: "winter", chinese: "冬天" },
        { english: "morning", chinese: "早晨" },
        { english: "afternoon", chinese: "下午" },
        { english: "evening", chinese: "傍晚" },
        { english: "night", chinese: "夜晚" },
        { english: "today", chinese: "今天" },
        { english: "tomorrow", chinese: "明天" },
        { english: "yesterday", chinese: "昨天" },
        { english: "hour", chinese: "小时" },
        { english: "minute", chinese: "分钟" },
        { english: "second", chinese: "秒" },
        { english: "week", chinese: "星期" },
        { english: "month", chinese: "月份" },
        { english: "year", chinese: "年" },
        { english: "century", chinese: "世纪" },
        { english: "time", chinese: "时间" },
        { english: "north", chinese: "北方" },
        { english: "south", chinese: "南方" },
        { english: "east", chinese: "东方" },
        { english: "west", chinese: "西方" },
        { english: "up", chinese: "上" },
        { english: "down", chinese: "下" },
        { english: "left", chinese: "左" },
        { english: "right", chinese: "右" },
        { english: "front", chinese: "前面" },
        { english: "back", chinese: "后面" },
        { english: "red", chinese: "红色" },
        { english: "green", chinese: "绿色" },
        { english: "blue", chinese: "蓝色" },
        { english: "yellow", chinese: "黄色" },
        { english: "black", chinese: "黑色" },
        { english: "white", chinese: "白色" },
        { english: "orange", chinese: "橙色" },
        { english: "purple", chinese: "紫色" },
        { english: "pink", chinese: "粉色" },
        { english: "brown", chinese: "棕色" },
        { english: "one", chinese: "一" },
        { english: "two", chinese: "二" },
        { english: "three", chinese: "三" },
        { english: "four", chinese: "四" },
        { english: "five", chinese: "五" },
        { english: "six", chinese: "六" },
        { english: "seven", chinese: "七" },
        { english: "eight", chinese: "八" },
        { english: "nine", chinese: "九" },
        { english: "ten", chinese: "十" },
        { english: "hundred", chinese: "百" },
        { english: "thousand", chinese: "千" },
        { english: "million", chinese: "百万" },
        { english: "billion", chinese: "十亿" },
        { english: "first", chinese: "第一" },
        { english: "last", chinese: "最后" },
        { english: "next", chinese: "下一个" },
        { english: "previous", chinese: "上一个" }
    ]
};
